[package]
name = "truthbyte-desktop"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2" }
truthbyte = { path = ".." }
